name: school_management
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  dropdown_search: ^5.0.6
  date_time_picker: ^2.1.0
  fzregex: ^2.0.0
  firebase_core: ^2.24.2
  flutter_svg: ^2.0.10+1
  flare_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/notification.png
    - assets/
